name: Gaia
description: Arena management plugin
author: Moros
version: ${pluginVersion}
load: POSTWORLD
main: me.moros.gaia.paper.GaiaBootstrap
depend: [WorldEdit]
api-version: 1.18
permissions:
  gaia.command.version:
    default: true
    description: Allows to view info about Gaia
  gaia.admin:
    default: op
    description: Grants access to all administrative gaia commands
    children:
      gaia.command.list: true
      gaia.command.info: true
      gaia.command.create: true
      gaia.command.remove: true
      gaia.command.revert: true
      gaia.command.cancel: true
      gaia.command.version: true
      gaia.command.reload: true
      gaia.command.bypass: true
      gaia.command.point: true
      gaia.command.teleport: true
